// ============================================================================
// Demo data — used when Supabase is not configured yet.
// Lets you explore the full UI immediately. Replace with real data by
// configuring Supabase (see .env.local.example).
// ============================================================================

import type {
  AnalyticsData,
  Appointment,
  AiChatMessage,
  AiUsage,
  Doctor,
  EmergencyContact,
  Hospital,
  Medicine,
  Prescription,
  Reminder,
  Report,
  AppNotification,
  UserProfile,
} from "@/types";

export const DEMO_USER: UserProfile = {
  id: "demo-user",
  email: "demo@healthcare.app",
  full_name: "Alex Johnson",
  avatar_url: null,
  role: "patient",
  phone: "+91 98765 43210",
  gender: "Male",
  date_of_birth: "1992-05-14",
  blood_group: "O+",
  height_cm: 175,
  weight_kg: 74,
  chronic_diseases: ["Hypertension"],
  allergies: ["Penicillin", "Peanuts"],
  address: "42 Sunrise Apartments, Indiranagar, Bengaluru",
  emergency_contact: { name: "Sarah Johnson", relation: "Wife", phone: "+91 91234 56780" },
  settings: {
    theme: "system",
    notifications: true,
    email_notifications: true,
    push_notifications: true,
    language: "en",
    two_factor: false,
    share_emergency: true,
    privacy: "private",
  },
  created_at: "2024-01-10T09:00:00Z",
  updated_at: "2025-12-01T09:00:00Z",
};

export const DEMO_HOSPITALS: Hospital[] = [
  {
    id: "h1",
    name: "Fortis Hospital",
    slug: "fortis-hospital-cunningham-road",
    description: "Tertiary care hospital on Cunningham Road with cardiac sciences, neurology and advanced emergency care.",
    address: "154/9, Opposite IIM, Cunningham Road",
    city: "Bengaluru",
    state: "Karnataka",
    phone: "+91 80 4114 4114",
    email: "bengaluru@fortishealthcare.com",
    website: "https://www.fortishealthcare.com/pan-india/hospitals/fortis-hospital-cunningham-road",
    latitude: 12.9815,
    longitude: 77.5965,
    specialities: ["Cardiology", "Neurology", "Orthopedics", "Nephrology", "Gastroenterology", "Emergency"],
    services: ["24/7 Emergency", "Ambulance", "ICU", "Cath Lab", "Pharmacy", "Diagnostics"],
    rating: 4.7,
    reviews_count: 1240,
    emergency: true,
    image_url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d",
    opening_hours: { "Mon-Sun": "00:00-23:59" },
    is_active: true,
  },
  {
    id: "h2",
    name: "Apollo Hospitals",
    slug: "apollo-hospitals-bannerghatta",
    description: "One of India's largest private hospital networks on Bannerghatta Road — cardiac sciences, oncology, transplants and 24/7 emergency.",
    address: "154/11, Bannerghatta Road",
    city: "Bengaluru",
    state: "Karnataka",
    phone: "+91 80 4182 1000",
    email: "care@apollohospitals.com",
    website: "https://www.apollohospitals.com/bengaluru/",
    latitude: 12.8894,
    longitude: 77.6047,
    specialities: ["Cardiology", "Oncology", "Neurology", "Nephrology", "General Medicine", "Emergency"],
    services: ["24/7 Emergency", "ICU", "Ambulance", "Pharmacy", "Diagnostics", "Health Checkups"],
    rating: 4.8,
    reviews_count: 2080,
    emergency: true,
    image_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514",
    opening_hours: { "Mon-Sun": "00:00-23:59" },
    is_active: true,
  },
  {
    id: "h3",
    name: "Manipal Hospital",
    slug: "manipal-hospital-old-airport-road",
    description: "Multi-speciality hospital on Old Airport Road — comprehensive care across cardiac, orthopedics, women and child health.",
    address: "98, HAL Airport Road",
    city: "Bengaluru",
    state: "Karnataka",
    phone: "+91 80 2502 4444",
    email: "info@manipalhospitals.com",
    website: "https://www.manipalhospitals.com/oldairportroad/",
    latitude: 12.9614,
    longitude: 77.656,
    specialities: ["Cardiology", "Orthopedics", "Neurology", "Gynecology", "Pediatrics", "General Medicine"],
    services: ["24/7 Emergency", "ICU", "OPD", "Pharmacy", "Diagnostics", "Maternity"],
    rating: 4.6,
    reviews_count: 860,
    emergency: true,
    image_url: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3",
    opening_hours: { "Mon-Sun": "00:00-23:59" },
    is_active: true,
  },
  {
    id: "h4",
    name: "Sparsh Hospital",
    slug: "sparsh-hospital-bannerghatta",
    description: "Specialist centre for orthopedics, spine surgery, sports medicine and physiotherapy on Bannerghatta Road.",
    address: "14, 100 Feet Road, Bannerghatta Road",
    city: "Bengaluru",
    state: "Karnataka",
    phone: "+91 80 4659 9999",
    email: "contact@sparshhospital.com",
    website: "https://www.sparshhospital.com/",
    latitude: 12.9205,
    longitude: 77.5885,
    specialities: ["Orthopedics", "Spine Surgery", "Sports Medicine", "Rheumatology", "Physiotherapy"],
    services: ["Surgery", "Physiotherapy", "X-Ray", "MRI", "Rehab", "Emergency"],
    rating: 4.6,
    reviews_count: 540,
    emergency: true,
    image_url: "https://images.unsplash.com/photo-1504439468489-c8920d796a29",
    opening_hours: { "Mon-Sun": "00:00-23:59" },
    is_active: true,
  },
  {
    id: "h5",
    name: "Narayana Health City",
    slug: "narayana-health-city",
    description: "One of the world's largest cardiac care centres at Bommasandra — cardiac surgery, neurology and organ transplants.",
    address: "#258/A, Bommasandra Industrial Area, Hosur Road",
    city: "Bengaluru",
    state: "Karnataka",
    phone: "+91 80 7122 2222",
    email: "contact@narayanahealth.org",
    website: "https://www.narayanahealth.org/",
    latitude: 12.837,
    longitude: 77.6608,
    specialities: ["Cardiology", "Cardiac Surgery", "Neurology", "Nephrology", "Transplant Surgery", "Emergency"],
    services: ["24/7 Emergency", "Cath Lab", "ICU", "Ambulance", "Pharmacy", "Diagnostics"],
    rating: 4.9,
    reviews_count: 1875,
    emergency: true,
    image_url: "https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd",
    opening_hours: { "Mon-Sun": "00:00-23:59" },
    is_active: true,
  },
  {
    id: "h6",
    name: "Motherhood Hospitals",
    slug: "motherhood-hospitals-indiranagar",
    description: "Maternity, women and child care hospital with NICU, IVF and lactation support at Indiranagar.",
    address: "No. 542, 1st Floor, 100 Feet Road, Indiranagar",
    city: "Bengaluru",
    state: "Karnataka",
    phone: "+91 80 4668 2600",
    email: "care@motherhoodhospitals.com",
    website: "https://www.motherhoodhospitals.com/",
    latitude: 12.9719,
    longitude: 77.6412,
    specialities: ["Obstetrics", "Gynecology", "Pediatrics", "Neonatology", "IVF"],
    services: ["NICU", "IVF", "Maternity", "Lactation", "Vaccination", "OPD"],
    rating: 4.5,
    reviews_count: 1110,
    emergency: true,
    image_url: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2",
    opening_hours: { "Mon-Sun": "00:00-23:59" },
    is_active: true,
  },
  {
    id: "h7",
    name: "Narayana Nethralaya",
    slug: "narayana-nethralaya",
    description: "Pioneering eye care institute specialising in retina, cataract, LASIK and neuro-ophthalmology.",
    address: "121, Chowdeshwari Layout, 1st R Block, Rajajinagar",
    city: "Bengaluru",
    state: "Karnataka",
    phone: "+91 80 6612 3737",
    email: "info@narayananethralaya.com",
    website: "https://www.narayananethralaya.com/",
    latitude: 12.9674,
    longitude: 77.5385,
    specialities: ["Ophthalmology", "Retina", "Neuro-Ophthalmology"],
    services: ["Cataract", "Lasik", "Retina Clinic", "Diagnostics", "OPD"],
    rating: 4.7,
    reviews_count: 320,
    emergency: false,
    image_url: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d",
    opening_hours: { "Mon-Sat": "09:00-19:00", Sun: "09:00-13:00" },
    is_active: true,
  },
  {
    id: "h8",
    name: "Aster CMI Hospital",
    slug: "aster-cmi-hospital-hebbal",
    description: "Multi-speciality quaternary care hospital at Hebbal — cardiac, neurosciences, orthopedics and liver care.",
    address: "No. 43/2, NH-44, Hebbal",
    city: "Bengaluru",
    state: "Karnataka",
    phone: "+91 80 4342 1000",
    email: "ask@asterhospitals.in",
    website: "https://www.asterhospitals.in/aster-cmi-hebbal",
    latitude: 13.0333,
    longitude: 77.5975,
    specialities: ["Cardiology", "Neurosciences", "Orthopedics", "Gastroenterology", "Transplant Surgery", "Emergency"],
    services: ["24/7 Emergency", "ICU", "Ambulance", "Pharmacy", "Diagnostics", "Health Checkups"],
    rating: 4.6,
    reviews_count: 690,
    emergency: true,
    image_url: "https://images.unsplash.com/photo-1581056771392-8a90ddb98731",
    opening_hours: { "Mon-Sun": "00:00-23:59" },
    is_active: true,
  },
];

const DOCTOR_NAMES: Record<string, [string, string, number, string][]> = {
  Cardiology: [["Dr. Arjun Mehta", "MD, DM Cardiology - AIIMS", 15, "Interventional cardiologist specialising in angioplasty and preventive cardiology."]],
  Neurology: [["Dr. Suresh Nair", "DM Neurology - NIMHANS", 18, "Stroke and epilepsy specialist with 10,000+ cases managed."]],
  Orthopedics: [["Dr. Rohan Iyer", "MS Ortho, Fellowship Sports Medicine", 13, "Knee and shoulder specialist, treats sports injuries and arthritis."]],
  Pediatrics: [["Dr. Priya Sharma", "MD Pediatrics - CMC Vellore", 11, "Child specialist focused on growth tracking, vaccines and nutrition."]],
  Dermatology: [["Dr. Neha Kapoor", "MD Dermatology, DNB", 9, "Clinical dermatologist and cosmetologist, treats acne and skin allergies."]],
  Gynecology: [["Dr. Kavita Reddy", "MD Obstetrics & Gynae", 12, "High-risk pregnancy and minimally invasive gynae surgery expert."]],
  Oncology: [["Dr. Amitabh Rao", "MD, DM Medical Oncology", 16, "Medical oncologist specialising in solid tumours and precision oncology."]],
  Endocrinology: [["Dr. Farah Khan", "DM Endocrinology - PGIMER", 10, "Diabetes, thyroid and hormonal disorder specialist."]],
  Gastroenterology: [["Dr. Karan Shah", "DM Gastroenterology", 11, "Endoscopist treating acid reflux, ulcers and liver disease."]],
  Ophthalmology: [["Dr. Ananya Singh", "MS Ophthalmology", 9, "Cataract and LASIK surgeon with modern phaco techniques."]],
  ENT: [["Dr. Rahul Verma", "MS ENT", 7, "Sinus, ear and voice disorder specialist."]],
  Urology: [["Dr. Imran Sheikh", "MCh Urology", 15, "Minimally invasive urology and stone disease specialist."]],
  "General Medicine": [["Dr. Meera Pillai", "MBBS, MD Internal Medicine", 8, "General physician managing diabetes, hypertension and infections."]],
  Physiotherapy: [["Dr. Pooja Malhotra", "MPT - Ortho & Sports", 6, "Sports rehab and post-surgical physiotherapist."]],
  Diabetology: [["Dr. Lakshmi Narayanan", "MD, DDM", 10, "Diabetes educator and lifestyle medicine practitioner."]],
  "Sports Medicine": [["Dr. Rohan Iyer", "MS Ortho", 13, "Sports injury and rehabilitation specialist."]],
  "Preventive Care": [["Dr. Farah Khan", "DM Endocrinology", 10, "Preventive health and lifestyle medicine."]],
  Nephrology: [["Dr. Nisha Reddy", "DM Nephrology", 12, "Kidney and dialysis care specialist."]],
  "Cardiac Surgery": [["Dr. Arjun Mehta", "MCh Cardiac Surgery", 16, "Cardiothoracic surgeon."]],
  Neonatology: [["Dr. Kavita Reddy", "DM Neonatology", 10, "Newborn intensive care specialist."]],
  IVF: [["Dr. Priya Sharma", "MSc, DNB Reproductive Medicine", 8, "Fertility and IVF specialist."]],
  Rheumatology: [["Dr. Neha Kapoor", "DM Rheumatology", 9, "Autoimmune and joint disease specialist."]],
  Emergency: [["Dr. Vikram Bhat", "MD Emergency Medicine", 10, "Emergency physician, trauma and critical care."]],
};

export function buildDemoDoctors(): Doctor[] {
  let id = 0;
  const doctors: Doctor[] = [];
  for (const hospital of DEMO_HOSPITALS) {
    for (const spec of hospital.specialities.slice(0, 3)) {
      const pool = DOCTOR_NAMES[spec] ?? [["Dr. John Doe", "MBBS, MD", 8, "General specialist."]];
      const [name, quals, exp, bio] = pool[hospital.id.charCodeAt(1) % pool.length] ?? pool[0];
      doctors.push({
        id: `d${++id}`,
        hospital_id: hospital.id,
        hospital,
        name,
        speciality: spec,
        qualifications: quals,
        experience_years: exp,
        fee: 400 + ((id * 37) % 5) * 125,
        rating: 4.4 + ((id * 13) % 5) / 10,
        bio,
        avatar_url: null,
        available_days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
        available_from: "09:00",
        available_to: "17:00",
      });
    }
  }
  return doctors;
}

export const DEMO_DOCTORS: Doctor[] = buildDemoDoctors();

const now = new Date();
const iso = (daysFromNow: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString();
};
const dateOnly = (daysFromNow: number) => iso(daysFromNow).split("T")[0];

export const DEMO_APPOINTMENTS: Appointment[] = [
  {
    id: "a1",
    patient_id: DEMO_USER.id,
    hospital_id: "h1",
    doctor_id: "d1",
    appointment_date: dateOnly(1),
    start_time: "10:30",
    end_time: "11:00",
    type: "in-person",
    status: "confirmed",
    reason: "Routine BP check-up and medication review.",
    notes: null,
    created_at: iso(-3),
    doctor: DEMO_DOCTORS.find((d) => d.id === "d1"),
    hospital: DEMO_HOSPITALS[0],
  },
  {
    id: "a2",
    patient_id: DEMO_USER.id,
    hospital_id: "h2",
    doctor_id: "d2",
    appointment_date: dateOnly(4),
    start_time: "16:00",
    end_time: "16:30",
    type: "video",
    status: "pending",
    reason: "Follow-up for blood sugar levels.",
    notes: null,
    created_at: iso(-1),
    doctor: DEMO_DOCTORS.find((d) => d.id === "d2"),
    hospital: DEMO_HOSPITALS[1],
  },
  {
    id: "a3",
    patient_id: DEMO_USER.id,
    hospital_id: "h4",
    doctor_id: "d3",
    appointment_date: dateOnly(-10),
    start_time: "11:00",
    end_time: "11:30",
    type: "in-person",
    status: "completed",
    reason: "Knee pain after running.",
    notes: "Recommended physiotherapy.",
    created_at: iso(-14),
    doctor: DEMO_DOCTORS.find((d) => d.id === "d3"),
    hospital: DEMO_HOSPITALS[3],
  },
  {
    id: "a4",
    patient_id: DEMO_USER.id,
    hospital_id: "h5",
    doctor_id: "d4",
    appointment_date: dateOnly(-25),
    start_time: "09:00",
    end_time: "09:30",
    type: "in-person",
    status: "cancelled",
    reason: "Annual heart screening.",
    notes: "Rescheduled by patient.",
    created_at: iso(-30),
    doctor: DEMO_DOCTORS.find((d) => d.id === "d4"),
    hospital: DEMO_HOSPITALS[4],
  },
];

export const DEMO_REPORTS: Report[] = [
  {
    id: "r1",
    patient_id: DEMO_USER.id,
    title: "Complete Blood Count — Jan 2026",
    category: "blood_report",
    description: "CBC panel with all values in normal range except slight iron deficiency.",
    lab_name: "MedPlus Diagnostics",
    report_date: dateOnly(-21),
    file_url: null,
    file_type: "pdf",
    file_size: 245000,
    created_at: iso(-21),
  },
  {
    id: "r2",
    patient_id: DEMO_USER.id,
    title: "Chest X-Ray — Annual Check",
    category: "xray",
    description: "Normal chest X-ray, no abnormalities detected.",
    lab_name: "City Care Radiology",
    report_date: dateOnly(-12),
    file_url: null,
    file_type: "image",
    file_size: 1180000,
    created_at: iso(-12),
  },
  {
    id: "r3",
    patient_id: DEMO_USER.id,
    title: "MRI Knee — Right",
    category: "mri",
    description: "Mild patellar tendinopathy. No ligament tear.",
    lab_name: "Sunrise Imaging",
    report_date: dateOnly(-9),
    file_url: null,
    file_type: "image",
    file_size: 4200000,
    created_at: iso(-9),
  },
  {
    id: "r4",
    patient_id: DEMO_USER.id,
    title: "Lipid Profile Report",
    category: "blood_report",
    description: "Cholesterol slightly elevated. LDL 145 mg/dL. Follow-up in 3 months.",
    lab_name: "Apollo Labs",
    report_date: dateOnly(-30),
    file_url: null,
    file_type: "pdf",
    file_size: 187000,
    created_at: iso(-30),
  },
  {
    id: "r5",
    patient_id: DEMO_USER.id,
    title: "Hepatitis B Vaccination — Dose 3",
    category: "vaccination",
    description: "Third dose administered. Series complete.",
    lab_name: "Green Leaf Vaccination Clinic",
    report_date: dateOnly(-60),
    file_url: null,
    file_type: "pdf",
    file_size: 98000,
    created_at: iso(-60),
  },
  {
    id: "r6",
    patient_id: DEMO_USER.id,
    title: "Allergy Test Report",
    category: "allergy",
    description: "Positive reaction to Penicillin and Peanuts.",
    lab_name: "City Care Allergy Clinic",
    report_date: dateOnly(-120),
    file_url: null,
    file_type: "pdf",
    file_size: 150000,
    created_at: iso(-120),
  },
];

export const DEMO_PRESCRIPTIONS: Prescription[] = [
  {
    id: "p1",
    patient_id: DEMO_USER.id,
    doctor_id: "d1",
    hospital_id: "h1",
    medication: "Amlodipine 5mg",
    dosage: "5 mg",
    frequency: "Once daily",
    duration: "3 months",
    notes: "Take after breakfast. Monitor BP weekly.",
    prescribed_date: dateOnly(-10),
    file_url: null,
    doctor: DEMO_DOCTORS.find((d) => d.id === "d1"),
  },
  {
    id: "p2",
    patient_id: DEMO_USER.id,
    doctor_id: "d4",
    hospital_id: "h2",
    medication: "Vitamin D3 60K",
    dosage: "1 tablet weekly",
    frequency: "Weekly",
    duration: "8 weeks",
    notes: "Take with milk or fatty meal.",
    prescribed_date: dateOnly(-30),
    file_url: null,
    doctor: DEMO_DOCTORS.find((d) => d.id === "d4"),
  },
];

export const DEMO_MEDICINES: Medicine[] = [
  {
    id: "m1",
    patient_id: DEMO_USER.id,
    name: "Amlodipine 5mg",
    dosage: "5 mg",
    frequency: "once_daily",
    times: ["09:00"],
    start_date: dateOnly(-10),
    end_date: dateOnly(80),
    notes: "For blood pressure. Take after breakfast.",
    active: true,
    created_at: iso(-10),
  },
  {
    id: "m2",
    patient_id: DEMO_USER.id,
    name: "Vitamin D3 60K",
    dosage: "1 tablet",
    frequency: "weekly",
    times: ["09:00"],
    start_date: dateOnly(-30),
    end_date: dateOnly(26),
    notes: "Take with fatty meal.",
    active: true,
    created_at: iso(-30),
  },
  {
    id: "m3",
    patient_id: DEMO_USER.id,
    name: "Paracetamol 650mg",
    dosage: "650 mg",
    frequency: "as_needed",
    times: [],
    start_date: dateOnly(-4),
    end_date: null,
    notes: "For fever/headache. Max 3/day.",
    active: false,
    created_at: iso(-4),
  },
];

export const DEMO_REMINDERS: Reminder[] = [
  {
    id: "rem1",
    patient_id: DEMO_USER.id,
    medicine_id: "m1",
    scheduled_at: new Date(new Date(iso(0)).setHours(9, 0, 0, 0)).toISOString(),
    status: "pending",
    taken_at: null,
    medicine: DEMO_MEDICINES[0],
  },
  {
    id: "rem2",
    patient_id: DEMO_USER.id,
    medicine_id: "m1",
    scheduled_at: new Date(new Date(iso(-1)).setHours(9, 0, 0, 0)).toISOString(),
    status: "taken",
    taken_at: new Date(new Date(iso(-1)).setHours(9, 12, 0, 0)).toISOString(),
    medicine: DEMO_MEDICINES[0],
  },
  {
    id: "rem3",
    patient_id: DEMO_USER.id,
    medicine_id: "m2",
    scheduled_at: new Date(new Date(iso(2)).setHours(9, 0, 0, 0)).toISOString(),
    status: "pending",
    taken_at: null,
    medicine: DEMO_MEDICINES[1],
  },
  {
    id: "rem4",
    patient_id: DEMO_USER.id,
    medicine_id: "m1",
    scheduled_at: new Date(new Date(iso(-2)).setHours(9, 0, 0, 0)).toISOString(),
    status: "missed",
    taken_at: null,
    medicine: DEMO_MEDICINES[0],
  },
];

export const DEMO_EMERGENCY_CONTACTS: EmergencyContact[] = [
  { id: "ec1", patient_id: DEMO_USER.id, name: "Sarah Johnson", relation: "Wife", phone: "+91 91234 56780", email: "sarah.johnson@example.com" },
  { id: "ec2", patient_id: DEMO_USER.id, name: "Mike Johnson", relation: "Brother", phone: "+91 99887 66554", email: "mike.johnson@example.com" },
];

export const DEMO_NOTIFICATIONS: AppNotification[] = [
  { id: "n1", user_id: DEMO_USER.id, title: "Appointment confirmed", message: "Your appointment with Dr. Arjun Mehta on Friday is confirmed.", type: "appointment", link: "/dashboard/appointments", is_read: false, created_at: iso(0) },
  { id: "n2", user_id: DEMO_USER.id, title: "Medicine reminder", message: "It's time to take Amlodipine 5mg.", type: "reminder", link: "/dashboard/medicines", is_read: false, created_at: iso(0) },
  { id: "n3", user_id: DEMO_USER.id, title: "New report uploaded", message: "Your MRI Knee report is available in Health Records.", type: "info", link: "/dashboard/records", is_read: true, created_at: iso(-1) },
  { id: "n4", user_id: DEMO_USER.id, title: "Welcome to Health Care", message: "Set up your medical profile and emergency contacts to get started.", type: "system", link: "/dashboard/profile", is_read: true, created_at: iso(-15) },
];

export const DEMO_CHAT: AiChatMessage[] = [
  {
    id: "c1",
    role: "assistant",
    content:
      "Hello! 👋 I'm your AI health assistant. I can help you understand symptoms, explain your medical reports, suggest the right specialist, and share preventive health tips. Remember, I'm not a replacement for professional medical advice — for emergencies, please call your local emergency number.",
    created_at: iso(0),
  },
];

export const DEMO_AI_USAGE: AiUsage[] = Array.from({ length: 30 }, (_, i) => ({
  id: `aiu${i}`,
  user_id: DEMO_USER.id,
  action: ["general", "symptom", "report", "specialist"][i % 4],
  model: "gemini-1.5-flash",
  tokens_in: 150 + Math.floor(Math.random() * 600),
  tokens_out: 100 + Math.floor(Math.random() * 400),
  latency_ms: 800 + Math.floor(Math.random() * 1500),
  created_at: new Date(now.getTime() - i * 24 * 3600 * 1000).toISOString(),
}));

export const DEMO_ANALYTICS: AnalyticsData = {
  totalPatients: 18240,
  totalDoctors: 312,
  totalHospitals: 128,
  totalAppointments: 45678,
  revenue: 12450000,
  appointmentsTrend: [
    { month: "Aug", appointments: 3200 },
    { month: "Sep", appointments: 3800 },
    { month: "Oct", appointments: 3600 },
    { month: "Nov", appointments: 4300 },
    { month: "Dec", appointments: 4900 },
    { month: "Jan", appointments: 5400 },
  ],
  patientGrowth: [
    { month: "Aug", patients: 9800 },
    { month: "Sep", patients: 11200 },
    { month: "Oct", patients: 12600 },
    { month: "Nov", patients: 14200 },
    { month: "Dec", patients: 16300 },
    { month: "Jan", patients: 18240 },
  ],
  specialityDistribution: [
    { name: "Cardiology", value: 28 },
    { name: "Orthopedics", value: 22 },
    { name: "Dermatology", value: 18 },
    { name: "Pediatrics", value: 15 },
    { name: "Neurology", value: 10 },
    { name: "Others", value: 7 },
  ],
  aiUsage: [
    { action: "Symptom check", tokens_in: 4200, tokens_out: 1800, count: 1240 },
    { action: "Report explanation", tokens_in: 3100, tokens_out: 1400, count: 860 },
    { action: "Specialist suggestion", tokens_in: 1800, tokens_out: 900, count: 640 },
    { action: "Preventive tips", tokens_in: 2300, tokens_out: 1100, count: 720 },
  ],
  statusDistribution: [
    { status: "confirmed", count: 3200 },
    { status: "completed", count: 5400 },
    { status: "pending", count: 900 },
    { status: "cancelled", count: 450 },
    { status: "no_show", count: 180 },
  ],
};

/** Demo admin lists for tables. */
export const DEMO_PATIENTS = [
  { id: "u1", full_name: "Alex Johnson", email: "demo@healthcare.app", phone: "+91 98765 43210", blood_group: "O+", appointments: 4, joined: "2024-01-10", status: "active" },
  { id: "u2", full_name: "Ananya Sharma", email: "ananya@example.com", phone: "+91 91234 11111", blood_group: "A+", appointments: 12, joined: "2024-02-18", status: "active" },
  { id: "u3", full_name: "Rohit Verma", email: "rohit@example.com", phone: "+91 91234 22222", blood_group: "B+", appointments: 7, joined: "2024-03-02", status: "active" },
  { id: "u4", full_name: "Kavya Nair", email: "kavya@example.com", phone: "+91 91234 33333", blood_group: "AB+", appointments: 2, joined: "2024-06-21", status: "inactive" },
  { id: "u5", full_name: "Aditya Gupta", email: "aditya@example.com", phone: "+91 91234 44444", blood_group: "O-", appointments: 9, joined: "2024-04-11", status: "active" },
  { id: "u6", full_name: "Sana Khan", email: "sana@example.com", phone: "+91 91234 55555", blood_group: "B-", appointments: 5, joined: "2024-08-30", status: "active" },
  { id: "u7", full_name: "Dev Patel", email: "dev@example.com", phone: "+91 91234 66666", blood_group: "A-", appointments: 1, joined: "2025-01-05", status: "active" },
  { id: "u8", full_name: "Ishita Rao", email: "ishita@example.com", phone: "+91 91234 77777", blood_group: "O+", appointments: 6, joined: "2024-05-17", status: "inactive" },
  { id: "u9", full_name: "Manav Joshi", email: "manav@example.com", phone: "+91 91234 88888", blood_group: "B+", appointments: 3, joined: "2024-09-09", status: "active" },
  { id: "u10", full_name: "Riya Menon", email: "riya@example.com", phone: "+91 91234 99999", blood_group: "AB-", appointments: 8, joined: "2024-07-14", status: "active" },
];
